from __future__ import annotations

from .models import MethodFamilyRole


BASE_METHOD_FAMILIES = (
    MethodFamilyRole(
        method_family_id="FS4-METHOD-01",
        stage_id="A",
        role="base_competitor",
        source_aliases=("TRAIN-1ST-LEGACY", "TRAIN-1ST-NEWFEATURE"),
        method_candidates=(
            "weighted_blend_top2",
            "weighted_blend_top3",
            "engineered_ridge",
            "engineered_bayesian_ridge",
            "engineered_huber",
        ),
        applicable_domains=("compression", "thermal", "vibration", "mechanical_energy"),
        feature_scope_policy=("xreg_core", "bcl_lattice_optional"),
        family_partial_branch=False,
        may_enter_outer_comparison=True,
        may_train_meta_model=False,
        status="likely_source_mapped_no_fit",
        notes="First-method weighted and engineered blend family; method number is not a quality rank.",
    ),
    MethodFamilyRole(
        method_family_id="FS4-METHOD-02",
        stage_id="B",
        role="base_competitor",
        source_aliases=("TRAIN-2ND-LEGACY", "TRAIN-2ND-NEWFEATURE"),
        method_candidates=(
            "baseline_stability",
            "stability_lasso_ridge",
            "spca_ridge",
            "spca_huber",
            "spca_pls",
            "block_pca_ridge",
            "bagged_subspace_ridge",
            "minimal_class_average",
            "multitask_screen_ridge",
            "multitask_screen_pls",
        ),
        applicable_domains=("compression", "thermal", "vibration", "mechanical_energy"),
        feature_scope_policy=("xreg_core", "bcl_lattice_optional"),
        family_partial_branch=False,
        may_enter_outer_comparison=True,
        may_train_meta_model=False,
        status="likely_source_mapped_no_fit",
        notes="SPCA/multitask candidates remain domain-conditional; filename hints are not superiority evidence.",
    ),
    MethodFamilyRole(
        method_family_id="FS4-METHOD-03",
        stage_id="C",
        role="base_competitor",
        source_aliases=("TRAIN-3RD-LEGACY", "TRAIN-3RD-NEWFEATURE"),
        method_candidates=(
            "direct_ard",
            "direct_elasticnet_cv",
            "direct_omp_ridge",
            "direct_quantile_median",
            "direct_theilsen",
            "direct_ransac_ridge",
            "direct_gpr_matern",
            "direct_gpr_rq",
            "residual_huber_krr",
            "residual_ard_krr",
            "residual_ridge_extratrees",
            "residual_pls_extratrees",
            "direct_extra_trees_shallow",
            "direct_random_forest_shallow",
            "direct_hist_gb",
            "direct_svr_rbf",
            "direct_svr_linear",
            "direct_knn_distance",
        ),
        applicable_domains=("compression", "thermal", "vibration", "mechanical_energy"),
        feature_scope_policy=("xreg_core", "bcl_lattice_optional"),
        family_partial_branch=False,
        may_enter_outer_comparison=True,
        may_train_meta_model=False,
        status="likely_source_mapped_no_fit",
        notes="Direct, robust, residual and shallow nonlinear candidates; complexity must remain inner-fold selected.",
    ),
    MethodFamilyRole(
        method_family_id="FS4-METHOD-04",
        stage_id="D",
        role="base_competitor_and_optional_oof_merger",
        source_aliases=("TRAIN-4TH-ENSEMBLE",),
        method_candidates=("featureaware_partial_missing_ensemble",),
        applicable_domains=("compression", "thermal", "vibration", "mechanical_energy"),
        feature_scope_policy=("xreg_core", "bcl_lattice_optional", "family_partial_branch"),
        family_partial_branch=True,
        may_enter_outer_comparison=True,
        may_train_meta_model=True,
        status="likely_source_mapped_no_fit",
        notes="B/C/L specialist and all-family core branches; any merger may consume inner-OOF predictions only.",
    ),
)


COORDINATOR_REFERENCE = MethodFamilyRole(
    method_family_id="FS4-COORDINATOR-05",
    stage_id="A+B+C+D",
    role="selection_coordinator_reference_not_competitor",
    source_aliases=("TRAIN-5TH-ALLTOGETHER", "TRAIN-5TH-FIXED"),
    method_candidates=("output_wise_exact_combo_selection",),
    applicable_domains=("compression", "thermal", "vibration", "mechanical_energy"),
    feature_scope_policy=("xreg_core", "bcl_lattice_optional", "family_partial_branch"),
    family_partial_branch=True,
    may_enter_outer_comparison=False,
    may_train_meta_model=False,
    status="likely_reference_requires_outer_wrapper",
    notes="Reused as orchestration evidence only. Its existing CV winner score is not an unbiased final estimate; add an outer wrapper.",
)
